#!/usr/bin/env bash
# Installs Nginx with the following config:
#+    Listens on port 80.
#+    Returns a page with "Hello World!" when queried
#++    at the root with a curl GET request.

#  updates packages for available software packages.
apt-get update
# installs the Nginx web server.
apt-get install -y nginx

# Devs the /etc/nginx/html directory, which will serve as the document root dir for Nginx.
mkdir /etc/nginx/html
#  Devs empty index.html file inside the /etc/nginx/html dir.
touch /etc/nginx/html/index.html
#  sets the content of the index.html file to "Hello World!" using the echo command.
echo "Hello World!" > /etc/nginx/html/index.html
# Sets Nginx to listen on port 80 serving files from the /etc/nginx/html dir.
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Configuring a new server block for redirection
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirect

# Enabling the new site config
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/


# Test Nginx config and reload
sudo nginx -t
sudo service nginx reload
