#!/usr/bin/env bash
# Showing "To infinity and beyond" indefinitely that has
#+ a sleep 2 in between each iteration.
#   showing "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
