#!/usr/bin/env bash
# Displaying no. from 1 to 100 in list formt.
#   Displaying "FizzBuzz" when the no. is a multiple of 3 and 5.
#   Displaying "Fizz" when the no. is a multiple of 3.
#   Displaying "Buzz" when the no. is a multiple of 5.
#   Otherwise, displays the number.

for numb in {1..100}
do
  if (( numb % 3 == 0 && numb % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( numb % 3 == 0 ))
  then
    echo "Fizz"
  elif (( numb % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$numb"
  fi
done
