#!/usr/bin/env bash
# Displaying contents of the file `/etc/passwd`.
#   Only displaying the usernme, user id, and user home dir path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
