#!/bin/bash

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Update localhost entry to 127.0.0.2
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts

# Update facebook.com entry to 8.8.8.8
sudo sed -i 's/[0-9.]* facebook.com/8.8.8.8 facebook.com/' /etc/hosts

